//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfertaDeFarmacia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NombreMedicina
    {
        public int Id { get; set; }
        public int OfertaId { get; set; }
        public int MedicinaId { get; set; }
        public string Marca { get; set; }
        public string EstaActivo { get; set; }
        public long Costo { get; set; }
    
        public virtual Medicina Medicina { get; set; }
        public virtual Oferta Oferta { get; set; }
    }
}
