//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conveniente.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bslhackEntities : DbContext
    {
        public bslhackEntities()
            : base("name=bslhackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clinica> Clinicas { get; set; }
        public virtual DbSet<Farmacia> Farmacias { get; set; }
        public virtual DbSet<Medicina> Medicinas { get; set; }
        public virtual DbSet<NombreMedicina> NombreMedicinas { get; set; }
        public virtual DbSet<Oferta> Ofertas { get; set; }
        public virtual DbSet<Paciente> Pacientes { get; set; }
        public virtual DbSet<Prescripcion> Prescripcions { get; set; }
        public virtual DbSet<Trabajo> Trabajoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<UsuarioTrabajo> UsuarioTrabajoes { get; set; }
        public virtual DbSet<UsusarioFarmacia> UsusarioFarmacias { get; set; }
        public virtual DbSet<Seguro> Seguroes { get; set; }
    }
}
