//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conveniente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmacia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farmacia()
        {
            this.Ofertas = new HashSet<Oferta>();
            this.UsusarioFarmacias = new HashSet<UsusarioFarmacia>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Comuna { get; set; }
        public string Localidad { get; set; }
        public string Direccion { get; set; }
        public string HoraApertura { get; set; }
        public string HoraCierre { get; set; }
        public string Telefono { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public int Region { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificada { get; set; }
        public bool EstaActivo { get; set; }
        public string Regiona { get; set; }
        public string ComunaId { get; set; }
        public string LocalidadId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta> Ofertas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsusarioFarmacia> UsusarioFarmacias { get; set; }
    }
}
