//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conveniente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicina()
        {
            this.NombreMedicinas = new HashSet<NombreMedicina>();
        }
    
        public int Id { get; set; }
        public int PrescripcionId { get; set; }
        public string NombreMedicamento { get; set; }
        public Nullable<int> Dosis { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> Cada { get; set; }
        public string UnidadTiempo { get; set; }
        public Nullable<int> CantidadDias { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificada { get; set; }
        public bool EstaActivo { get; set; }
    
        public virtual Prescripcion Prescripcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NombreMedicina> NombreMedicinas { get; set; }
    }
}
